# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-08 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=20)),
                ('mobile_cost', models.FloatField()),
                ('mobile_desc', models.TextField()),
                ('mobile_img', models.ImageField(null=True, upload_to='mobile_image')),
            ],
        ),
    ]
