# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-16 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderTable',
        ),
    ]
