# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-17 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeshop', '0003_auto_20200617_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('ordertime', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='amount',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='mobile',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='zip_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
