# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-22 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeshop', '0005_contactdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop_name', models.CharField(max_length=50)),
                ('laptop_cost', models.FloatField()),
                ('laptop_desc', models.TextField()),
                ('laptop_img', models.ImageField(null=True, upload_to='laptop_image')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakerTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(max_length=50)),
                ('speaker_cost', models.FloatField()),
                ('speaker_desc', models.TextField()),
                ('speaker_img', models.ImageField(null=True, upload_to='speaker_image')),
            ],
        ),
    ]
