# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-23 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeshop', '0006_laptoptable_speakertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenJeansTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men_jeans_name', models.CharField(max_length=50)),
                ('men_jeans_cost', models.FloatField()),
                ('men_jeans_desc', models.TextField()),
                ('men_jeans_img', models.ImageField(null=True, upload_to='menjeans_image')),
            ],
        ),
        migrations.CreateModel(
            name='MenShirtTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men_shirt_name', models.CharField(max_length=50)),
                ('men_shirt_cost', models.FloatField()),
                ('men_shirt_desc', models.TextField()),
                ('men_shirt_img', models.ImageField(null=True, upload_to='menshirt_image')),
            ],
        ),
        migrations.CreateModel(
            name='MenTshirtTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men_tshirt_name', models.CharField(max_length=50)),
                ('men_tshirt_cost', models.FloatField()),
                ('men_tshirt_desc', models.TextField()),
                ('men_tshirt_img', models.ImageField(null=True, upload_to='mentshirt_image')),
            ],
        ),
        migrations.CreateModel(
            name='WomenJeansTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('women_jeans_name', models.CharField(max_length=50)),
                ('women_jeans_cost', models.FloatField()),
                ('women_jeans_desc', models.TextField()),
                ('women_jeans_img', models.ImageField(null=True, upload_to='womenjeans_image')),
            ],
        ),
        migrations.CreateModel(
            name='WomenKurtaTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('women_kurta_name', models.CharField(max_length=50)),
                ('women_kurta_cost', models.FloatField()),
                ('women_kurta_desc', models.TextField()),
                ('women_kurta_img', models.ImageField(null=True, upload_to='womenkurta_image')),
            ],
        ),
        migrations.CreateModel(
            name='WomenTshirtTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('women_tshirt_name', models.CharField(max_length=50)),
                ('women_tshirt_cost', models.FloatField()),
                ('women_tshirt_desc', models.TextField()),
                ('women_tshirt_img', models.ImageField(null=True, upload_to='womentshirt_image')),
            ],
        ),
    ]
