# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-23 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeshop', '0007_menjeanstable_menshirttable_mentshirttable_womenjeanstable_womenkurtatable_womentshirttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeshop.LaptopTable')),
                ('men_jeans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeshop.MenJeansTable')),
                ('men_shirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeshop.MenShirtTable')),
                ('men_tshirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeshop.MenTshirtTable')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeshop.MobileTable')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeshop.SpeakerTable')),
                ('women_jeans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeshop.WomenJeansTable')),
                ('women_kurta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeshop.WomenKurtaTable')),
                ('women_tshirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeshop.WomenTshirtTable')),
            ],
        ),
    ]
