# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-24 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeshop', '0008_allproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menjeanstable',
            name='men_jeans_img',
            field=models.ImageField(null=True, upload_to='menjns_image'),
        ),
        migrations.AlterField(
            model_name='menshirttable',
            name='men_shirt_img',
            field=models.ImageField(null=True, upload_to='mensrt_image'),
        ),
        migrations.AlterField(
            model_name='mentshirttable',
            name='men_tshirt_img',
            field=models.ImageField(null=True, upload_to='mentrt_image'),
        ),
        migrations.AlterField(
            model_name='womenjeanstable',
            name='women_jeans_img',
            field=models.ImageField(null=True, upload_to='womens_image'),
        ),
        migrations.AlterField(
            model_name='womenkurtatable',
            name='women_kurta_img',
            field=models.ImageField(null=True, upload_to='wometa_image'),
        ),
        migrations.AlterField(
            model_name='womentshirttable',
            name='women_tshirt_img',
            field=models.ImageField(null=True, upload_to='wo_trt_image'),
        ),
    ]
